### ISSUE TITLE
floating point invalid operation as 0x75b9cbb2

### ISSUE THREAD

**Issue by ericduarte** [r1me/TTesseractOCR4#4]
Hello

I'm getting this error while trying to create pdf from attached file.

I'm using portuguese language.

[input.zip](https://github.com/r1me/TTesseractOCR4/files/1506178/input.zip)

Thanks.

**Comment by r1me** [comment]
The issue is within Tesseract itself, we have already discussed it [here](https://github.com/r1me/TTesseractOCR4/issues/3). Please don't create issues related to this topic, until it is solved in Tesseract.

**Comment by ericduarte** [comment]
The error from topic you mentioned was resolved using the build you attached in it,i think this error is different and thought there might be a solution.
I tried using the tesseract.exe itself to create pdf and worked OK.

Thanks .

**Comment by r1me** [comment]
I've wrapped call to Tesseract's PDF renderer, with custom exception mask (it will ignore division by zero) so PDF is created successfully. The issue is still in the Tesseract, most likely in C interface, while C++ methods are handled differently, thus no error with `tesseract.exe`.

**Comment by ericduarte** [comment]
I found this solutio and, would suggest to you. 
I'm glad you changed it, in this commit.

Thanks for attention.
